package ir.mralizade.imdbshow.model.singlemovie

data class SingleMovieResponseModel(
    val id: String?,
    val fullTitle: String?,
    val title: String?,
    val image: String?,
    val imDbRating: String?,
    val imDbRatingVotes: String?,
    val companies: String?,
    val genres: String?,
    val languages: String?,
    val countries: String?,
    val stars: String?,
    val year: String?,
    val writers: String?,
    val directors: String?,
    val type: String?,
    val plot: String?,

    val actorList: List<Actor>?,
    val similars: List<Similar>?,
    val trailer: Trailer?,

    val awards: String?,
    val boxOffice: BoxOffice?,
    val companyList: List<Company>?,
    val contentRating: String?,
    val countryList: List<Country>?,
    val directorList: List<Director>?,
    val errorMessage: String?,
    val fullCast: Any?,
    val genreList: List<Genre>?,
    val images: Any?,
    val keywordList: List<String>?,
    val keywords: String?,
    val languageList: List<Language>?,
    val metacriticRating: String?,
    val originalTitle: String?,
    val plotLocal: String?,
    val plotLocalIsRtl: Boolean?,
    val posters: Any?,
    val ratings: Any?,
    val releaseDate: String?,
    val runtimeMins: String?,
    val runtimeStr: String?,
    val starList: List<Star>?,
    val tagline: String?,
    val tvEpisodeInfo: Any?,
    val tvSeriesInfo: Any?,
    val wikipedia: Any?,
    val writerList: List<Writer>?
)